- README.rst
> Fix user guide url error

- Language/pl/Validation.php
Related to my PR#1186 in official CI4 repo.
> valid_json

- Language/zh-CN/CLI.php
- Language/zh-CN/Cache.php
- Language/zh-CN/Cast.php
- Language/zh-CN/Core.php
- Language/zh-CN/Database.php
- Language/zh-CN/Files.php
- Language/zh-CN/Filters.php
- Language/zh-CN/Format.php
- Language/zh-CN/HTTP.php
- Language/zh-CN/Images.php
- Language/zh-CN/Language.php
- Language/zh-CN/Log.php
- Language/zh-CN/Migrations.php
- Language/zh-CN/Number.php
- Language/zh-CN/Pager.php
- Language/zh-CN/Router.php
- Language/zh-CN/Session.php
- Language/zh-CN/Time.php
- Language/zh-CN/Validation.php
- Language/zh-CN/View.php
Update chinese language for cache,cli,cast,core,database file
> WIP Provide chinese language translations

- Language/ar/CLI.php
- first translation
- added "commandNotFound" key
- changed indentation to match the English file
> CLI first translation

- MISSING.rst
- README.rst
- changelog.rst
> v4.0.0-beta.2

- Language/ru/Redirect.php
Update translation in Russian for CI4 in the file Redirect.php
> Update Russian translation for CodeIgniter4

- Language/sk/CLI.php
- Language/sk/Cache.php
- Language/sk/Cast.php
- Language/sk/Core.php
- Language/sk/Database.php
- Language/sk/Entity.php
- Language/sk/Files.php
- Language/sk/Filters.php
- Language/sk/Format.php
- Language/sk/HTTP.php
- Language/sk/Images.php
- Language/sk/Language.php
- Language/sk/Log.php
- Language/sk/Migrations.php
- Language/sk/Number.php
- Language/sk/Pager.php
- Language/sk/Redirect.php
- Language/sk/Router.php
- Language/sk/Session.php
- Language/sk/Time.php
- Language/sk/Validation.php
- Language/sk/View.php
- README.rst
Full Slovak translation of CI4 - beta 4
> Added Slovak language

- README.rst
- composer.json
- composer.lock
- phpunit
- phpunit.xml.dist
- tests/.htaccess
- tests/README.md
- tests/_support/CIUnitTestCase.php
- tests/_support/Language/MockLanguage.php
- tests/_support/Language/SecondMockLanguage.php
- tests/_support/Language/ab-CD/Allin.php
- tests/_support/Language/ab/Allin.php
- tests/_support/Language/en-ZZ/More.php
- tests/_support/Language/en/Allin.php
- tests/_support/Language/en/Core.php
- tests/_support/Language/en/More.php
- tests/_support/Language/ru/Language.php
- tests/_support/MockCodeIgniter.php
- tests/_support/MockCommon.php
- tests/_support/Services.php
- tests/_support/_bootstrap.php
- tests/system/Language/TranslationsTest.php
Fix composer autoload config.
Add unit testing for file & key completeness.
> Fix autoload; add unit tests

- Language/ja/CLI.php
- Language/ja/Cache.php
- Language/ja/Cast.php
- Language/ja/Core.php
- Language/ja/Database.php
- Language/ja/Email.php
- Language/ja/Encryption.php
- Language/ja/Entity.php
- Language/ja/Files.php
- Language/ja/Filters.php
- Language/ja/Format.php
- Language/ja/HTTP.php
- Language/ja/Images.php
- Language/ja/Language.php
- Language/ja/Log.php
- Language/ja/Migrations.php
- Language/ja/Number.php
- Language/ja/Pager.php
- Language/ja/RESTful.php
- Language/ja/Redirect.php
- Language/ja/Router.php
- Language/ja/Session.php
- Language/ja/Time.php
- Language/ja/Validation.php
- Language/ja/View.php
I've done Japanese translation.
Please review and comment.
> NEW LANGUAGE Added Japanese translations.

- Language/ko/CLI.php
- Language/ko/Cache.php
- Language/ko/Cast.php
- Language/ko/Core.php
- Language/ko/Database.php
- Language/ko/Email.php
- Language/ko/Encryption.php
- Language/ko/Entity.php
- Language/ko/Files.php
- Language/ko/Filters.php
- Language/ko/Format.php
- Language/ko/HTTP.php
- Language/ko/Images.php
- Language/ko/Language.php
- Language/ko/Log.php
- Language/ko/Migrations.php
- Language/ko/Number.php
- Language/ko/Pager.php
- Language/ko/RESTful.php
- Language/ko/Redirect.php
- Language/ko/Router.php
- Language/ko/Session.php
- Language/ko/Time.php
- Language/ko/Validation.php
- Language/ko/View.php
I've just update Korean language pack for CodeIgniter v4.0.0 and v4.0.2.
Could you merge that please?
> Update: Korean language pack for CI v4.0.0 and v4.0.2

- Language/vi/CLI.php
- Language/vi/Cache.php
- Language/vi/Cast.php
- Language/vi/Core.php
- Language/vi/Database.php
- Language/vi/Email.php
- Language/vi/Encryption.php
- Language/vi/Entity.php
- Language/vi/Files.php
- Language/vi/Filters.php
- Language/vi/Format.php
- Language/vi/HTTP.php
- Language/vi/Images.php
- Language/vi/Language.php
- Language/vi/Log.php
- Language/vi/Migrations.php
- Language/vi/Number.php
- Language/vi/Pager.php
- Language/vi/RESTful.php
- Language/vi/Redirect.php
- Language/vi/Router.php
- Language/vi/Session.php
- Language/vi/Time.php
- Language/vi/Validation.php
- Language/vi/View.php
I need more help from comunity. Thanks
> Add vi - Vietnamese

- Language/nl/CLI.php
- Language/nl/Cache.php
- Language/nl/Cast.php
- Language/nl/Core.php
- Language/nl/Database.php
- Language/nl/Email.php
- Language/nl/Encryption.php
- Language/nl/Entity.php
- Language/nl/Files.php
- Language/nl/Filters.php
- Language/nl/Format.php
- Language/nl/HTTP.php
- Language/nl/Images.php
- Language/nl/Language.php
- Language/nl/Log.php
- Language/nl/Migrations.php
- Language/nl/Number.php
- Language/nl/Pager.php
- Language/nl/RESTful.php
- Language/nl/Redirect.php
- Language/nl/Router.php
- Language/nl/Session.php
- Language/nl/Time.php
- Language/nl/Validation.php
- Language/nl/View.php
> Initial NL translation

- .travis.yml
- Language/pt-BR/Validation.php
Some files were out of date in relation to the RC3 "en" translation file.
> Update pt-BR translations

- Language/cs/CLI.php
- Language/cs/Cache.php
- Language/cs/Cast.php
- Language/cs/Core.php
- Language/cs/Database.php
- Language/cs/Email.php
- Language/cs/Encryption.php
- Language/cs/Entity.php
- Language/cs/Files.php
- Language/cs/Filters.php
- Language/cs/Format.php
- Language/cs/HTTP.php
- Language/cs/Images.php
- Language/cs/Language.php
- Language/cs/Log.php
- Language/cs/Migrations.php
- Language/cs/Number.php
- Language/cs/Pager.php
- Language/cs/RESTful.php
- Language/cs/Redirect.php
- Language/cs/Router.php
- Language/cs/Session.php
- Language/cs/Time.php
- Language/cs/Validation.php
- Language/cs/View.php
Hello,
I have added new translation files based on Slovak translation files. Some strings were not translated, so I translated all of missing strings to Czech. Hope it pass the tests and will be merged. Thanks.
> Czech translation

- Language/no/Number.php
This should be lowercased when the original is. Small design fix.
> [NO] Changed to lowercase in Number.php

- composer.json
In relation to https://github.com/codeigniter4/translations/pull/144#issuecomment-735385544
> Update php version constraint in composer.json

- Language/sv-SE/CLI.php
- Language/sv-SE/Cache.php
- Language/sv-SE/Cast.php
- Language/sv-SE/Core.php
- Language/sv-SE/Database.php
- Language/sv-SE/Email.php
- Language/sv-SE/Encryption.php
- Language/sv-SE/Entity.php
- Language/sv-SE/Fabricator.php
- Language/sv-SE/Files.php
- Language/sv-SE/Filters.php
- Language/sv-SE/Format.php
- Language/sv-SE/HTTP.php
- Language/sv-SE/Images.php
- Language/sv-SE/Language.php
- Language/sv-SE/Log.php
- Language/sv-SE/Migrations.php
- Language/sv-SE/Number.php
- Language/sv-SE/Pager.php
- Language/sv-SE/RESTful.php
- Language/sv-SE/Redirect.php
- Language/sv-SE/Router.php
- Language/sv-SE/Session.php
- Language/sv-SE/Time.php
- Language/sv-SE/Validation.php
- Language/sv-SE/View.php
- MISSING.rst
- README.md
- tests/Language/AbstractTranslationTestCase.php
- tests/Language/SwedishTranslationTest.php
Created a new fork based on develop and hopefully got everything right.
> New version of sv-SE

- Language/de/Email.php
- Language/de/Encryption.php
again, now with a clean commit history, without merge commits (replaces commit https://github.com/codeigniter4/translations/pull/164)
> [german] fixing spellings

- CONTRIBUTING.md
- composer.json
- tests/Language/AbstractTranslationTestCase.php
- tests/Language/AllLocalesTranslationTest.php
- tests/Language/ArabicTranslationTest.php
- tests/Language/BrazilianTranslationTest.php
- tests/Language/CzechTranslationTest.php
- tests/Language/DutchTranslationTest.php
- tests/Language/FarsiTranslationTest.php
- tests/Language/FrenchTranslationTest.php
- tests/Language/GermanTranslationTest.php
- tests/Language/IndonesianTranslationTest.php
- tests/Language/ItalianTranslationTest.php
- tests/Language/JapaneseTranslationTest.php
- tests/Language/KoreanTranslationTest.php
- tests/Language/LatvianTranslationTest.php
- tests/Language/LithuanianTranslationTest.php
- tests/Language/MalayalamTranslationTest.php
- tests/Language/NorwegianTranslationTest.php
- tests/Language/PolishTranslationTest.php
- tests/Language/PortugueseTranslationTest.php
- tests/Language/RussianTranslationTest.php
- tests/Language/SimpleChineseTranslationTest.php
- tests/Language/SlovakTranslationTest.php
- tests/Language/SpanishTranslationTest.php
- tests/Language/SwedishTranslationTest.php
- tests/Language/TraditionalChineseTranslationTest.php
- tests/Language/TurkishTranslationTest.php
- tests/Language/UkrainianTranslationTest.php
- tests/Language/VietnameseTranslationTest.php
> Fix namespace ignored by CI4 autoloader

- CONTRIBUTING.md
> Fix link to README

- Language/ja/Validation.php
Fixed a little oddity in the Japanese translation.
> Fix ja Validation.required translation

- Language/ja/CLI.php
- Language/ja/Database.php
- Language/ja/Fabricator.php
- Language/ja/HTTP.php
- Language/ja/Migrations.php
- Language/ja/Session.php
- Language/ja/Validation.php
- README.md
#148 and some little fixes.
```
$ ./phpunit --filter JapaneseTranslationTest
PHPUnit 9.5.0 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.13
Configuration: /Users/kenji/work/codeigniter/codeigniter4-translations/phpunit.xml.dist
...............................                                   31 / 31 (100%)
Time: 00:00.029, Memory: 14.00 MB
OK (31 tests, 31 assertions)
```
> Update lang ja string

- .github/workflows/build.yml
- .github/workflows/code-style.yml
~If..else would be reverted when fix passed.~
Seems working now..
> Fix push event on CI

- Language/ja/Core.php
- Language/ja/Images.php
- Language/ja/Security.php
Translated new items.
https://github.com/codeigniter4/translations/issues/148#issuecomment-740581171
```
$ vendor/bin/phpunit --filter JapaneseTranslationTest
PHPUnit 9.5.0 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.13
Configuration: /Users/kenji/work/codeigniter/codeigniter4-translations/phpunit.xml.dist
.......                                                             7 / 7 (100%)
Time: 00:00.161, Memory: 14.00 MB
OK (7 tests, 7 assertions)
```
> Update ja string

- Language/si/CLI.php
- Language/si/Cache.php
- Language/si/Cast.php
- Language/si/Core.php
- Language/si/Database.php
- Language/si/Email.php
- Language/si/Encryption.php
- Language/si/Fabricator.php
- Language/si/Files.php
- Language/si/Filters.php
- Language/si/Format.php
- Language/si/HTTP.php
- Language/si/Images.php
- Language/si/Log.php
- Language/si/Migrations.php
- Language/si/Number.php
- Language/si/Pager.php
- Language/si/RESTful.php
- Language/si/Router.php
- Language/si/Security.php
- Language/si/Session.php
- Language/si/Time.php
- Language/si/Validation.php
- Language/si/View.php
- README.md
- tests/Language/AbstractTranslationTestCase.php
- tests/Language/SinhalaTranslationTest.php
This PR includes complete Sinhala language translation. and I would like to be the maintainer for Sinhala language.
Best regards,
Nalaka Prasad
> Complete Sinhala language translation.

- Language/ja/Time.php
```
$ vendor/bin/phpunit --filter JapaneseTranslationTest
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.13
Configuration: /Users/kenji/work/codeigniter/codeigniter4-translations/phpunit.xml.dist
.......                                                             7 / 7 (100%)
Time: 00:00.181, Memory: 14.00 MB
OK (7 tests, 7 assertions)
```
> Add Time.invalidFormat for ja

- Language/sv-SE/Time.php
Added Time.invalidFormat from CI4 develop
> Added Time.invalidFormat for sv-SE

- Language/de/Time.php
> [DE] Add time.invalidFormat.

- Language/sv-SE/CLI.php
Updated the CLI strings for 4.1.1
> Translated the CLI strings from 4.1.1

- Language/ja/CLI.php
- Language/ja/Cast.php
- Language/ja/Cookie.php
- Language/ja/Email.php
- Language/ja/Format.php
- Language/ja/HTTP.php
- Language/ja/Log.php
- Translate new lang items
- Fix exsiting lang items
> Add new lang item translation for ja

- .github/scripts/continuous-integration
- Language/lv/CLI.php
- Language/lv/Cache.php
- Language/lv/Cast.php
- Language/lv/Cookie.php
- Language/lv/Core.php
- Language/lv/Database.php
- Language/lv/Email.php
- Language/lv/Encryption.php
- Language/lv/Fabricator.php
- Language/lv/Files.php
- Language/lv/Filters.php
- Language/lv/Format.php
- Language/lv/HTTP.php
- Language/lv/Images.php
- Language/lv/Log.php
- Language/lv/Migrations.php
- Language/lv/Number.php
- Language/lv/Pager.php
- Language/lv/RESTful.php
- Language/lv/Router.php
- Language/lv/Security.php
- Language/lv/Session.php
- Language/lv/Time.php
- Language/lv/Validation.php
- Language/lv/View.php
- README.md
- tests/Language/LatvianTranslationTest.php
LV language translation updates for v4.1.1
- new files: Cookie and Security
- language keys merged to perfectly match EN version
- each language key has original EN translation as comment
- updated test
- updated README file
> LV translation updates for v4.1.1

- Language/th/CLI.php
- Language/th/Cache.php
- Language/th/Cast.php
- Language/th/Cookie.php
- Language/th/Core.php
- Language/th/Database.php
- Language/th/Email.php
- Language/th/Encryption.php
- Language/th/Fabricator.php
- Language/th/Files.php
- Language/th/Filters.php
- Language/th/Format.php
- Language/th/HTTP.php
- Language/th/Images.php
- Language/th/Log.php
- Language/th/Migrations.php
- Language/th/Number.php
- Language/th/Pager.php
- Language/th/RESTful.php
- Language/th/Router.php
- Language/th/Security.php
- Language/th/Session.php
- Language/th/Time.php
- Language/th/Validation.php
- Language/th/View.php
- MISSING.rst
- README.md
- tests/Language/AbstractTranslationTestCase.php
- tests/Language/ThaiTranslationTest.php
- tests/Language/ThaiTranslationsTest.php
Hello,
I've finished translating the CI4 framework to the Thai language and would like to merge it back to the base repo. I've updated the `README.md` file also. But not sure if I gave the right version to it; I put the data in the `version` column as `4.0.3`. Feel free to give me feedback in case I did anything wrong.
> Thai translations

- Language/sv-SE/Cast.php
- Language/sv-SE/Cookie.php
- Language/sv-SE/Core.php
- Language/sv-SE/Log.php
Updated Cast, Cookie, Core and Log with strings from CI develop 2021-08-17.
> Updated the Swedish translations

- Language/de/Files.php
- Language/de/Publisher.php
- Language/de/Test.php
> Fix missing DE keys.

- .gitattributes
- .php-cs-fixer.dist.php
- bin/test
Check untranslated locales:
```
$ bin/test
```
Run test for specific locale:
```
$ bin/test ja
```
> chore: add script to check untranslated locales

- Language/sv-SE/Publisher.php
- Language/sv-SE/Test.php
PR to keep the sv-SE Language up to date with core development.
> Updated translations for sv-SE

- .github/scripts/continuous-integration
- .github/workflows/auto-review.yml
- LICENSE
- composer.json
- phpunit.xml.dist
- tests/AutoReview/TranslationsCodeTest.php
> Introduce Auto Review tests

- Language/id/CLI.php
- Language/id/Database.php
- Language/id/Encryption.php
- Language/id/Migrations.php
- Language/id/View.php
- translation file /id/CLI.php on 'cancelOperation'  to full bahasa
- translation file /id/CLI.php on 'commandType' to full bahasa
- fix typo bahasa file /id/CLI.php on 'usingCINamespace'
- fix typo bahasa file /id/Encryption on 'noHandlerAvailable'
Translated based on KBBI for language standardization
> Translation to Bahasa (ID) with changing typo

- Language/sv-SE/Database.php
- Language/sv-SE/Migrations.php
- Language/sv-SE/Router.php
- Language/sv-SE/View.php
Updating Swedish translations.
(I hope signing etc works - I have updated my dev machine, please let me know if there are any issues)
> Updating sv-SE with latest strings.

- Language/hu/Router.php
- Router.php add `invalidDynamicController` and `invalidControllerName`
> Router.php add missing param [HU]

- Language/ja/HTTP.php
> Update HTTP.invalidRoute in ja

- tests/AutoReview/TranslationsCodeTest.php
> Fix coding style

- Language/id/Validation.php
> Added missing item `valid_json` in `Validation` Indonesian 4.2.7

- Language/ja/Validation.php
> [ja] Add Validation.valid_json translation

- Language/sv-SE/Validation.php
Added missing validation string.
(Note: this was created on my new dev-machine so I hope everything is configured correctly for git and github, please let me know if anything is amiss)
> Updated sv-SE with missing valid_json

- bin/generate-page
- Adds colors to terminal output
- Splits words with spaces (e.g. SimplifiedChinese => Simplified Chinese)
> Improve outputs of bin/generate-page script

- Language/fa/Validation.php
> fix: add missing `valid_json` for Farsi

- Language/de/Errors.php
german translation file for strings added in 4.3
> [de] Create Errors.php

- Language/de/HTTP.php
replaces https://github.com/codeigniter4/translations/pull/361
> [de] add missing key and translation

- Language/ko/CLI.php
Adding missed messages that were not detected in test code
> [ko] CLI.generator.viewName.cell, CLI.generator.className.cell add

- tests/Language/AbstractTranslationTestCase.php
> Fix diffing of deeply nested array translations

- Language/ja/CLI.php
> [ja] Add CLI.generator.className.cell and CLI.generator.viewName.cell

- Language/fa/CLI.php
- Language/fa/Errors.php
- Language/fa/HTTP.php
> [fa] add `cell`, `localeNotSupported` and `Errors.php`

- Language/ru/Migrations.php
> [ru] correct key order

- README.md
See https://github.com/codeigniter4/translations/releases/tag/v4.3.1
> docs: fix sr version where the locale was released

- .github/workflows/auto-review.yml
- .github/workflows/build.yml
- .github/workflows/code-style.yml
Trying to fix intermittent failures on CI by using the workflows on coding-standard
> Fix intermittent failures on CI

- Language/it/CLI.php
- Language/it/Database.php
- Language/it/Errors.php
- Language/it/HTTP.php
- Language/it/Migrations.php
- Language/it/Router.php
- Language/it/Validation.php
- Language/it/View.php
Updated with nine new Italian strings.
> [it] Updated italian strings

- .github/workflows/generate-page.yml
Ref: https://github.com/actions/starter-workflows/blob/main/pages/static.yml
> Fix generate-page workflow

- Language/de/HTTP.php
Regarding:
https://github.com/codeigniter4/CodeIgniter4/pull/7370
> [de] Update HTTP.php

- Language/ja/Core.php
- Language/ja/HTTP.php
> [ja] Add and update translations for 4.4.0

- Language/de/Core.php
add missing translation string Core.invalidDirectory
> [de] Update Core.php

- Language/sv-SE/Core.php
Updated with missing string from Core.php
> Added missing string in Core.php

- .github/workflows/auto-review.yml
- .github/workflows/build.yml
- .github/workflows/code-style.yml
~From https://github.com/composer/composer/issues/8710#issuecomment-607710536~
**Checklist:**
> fix: add env.GITHUB_TOKEN to setup-php

- Language/ja/Language.php
- add new Language.php
**Checklist:**
> [ja] Add Language.php

- Language/de/Language.php
Added Language.invalidMessageFormat error message for 4.4.2 release of CodeIgniter4
> [de] Create Language.php

- Language/id/CLI.php
- Language/id/Core.php
- Language/id/Language.php
> feat: [ID] language update

- Language/pl/CLI.php
- Language/pl/Cookie.php
- Language/pl/Core.php
- Language/pl/Errors.php
- Language/pl/HTTP.php
- Language/pl/Language.php
This PR adds missing translation strings and fixes some typos.
**Checklist:**
> Polish translation update

- Language/ja/HTTP.php
> [ja] Add HTTP.invalidJSON and unsupportedJSONFormat for 4.4.4

- Language/fa/Number.php
'میلیون' is correct and common.
**Checklist:**
> [fa] Update Number.php

- Language/ko/HTTP.php
Add HTTP.invalidJSON and unsupportedJSONFormat
**Checklist:**
> [ko] Add HTTP.invalidJSON and unsupportedJSONFormat for 4.4.4

- Language/fa/HTTP.php
- Language/fa/Language.php
- bin/test
Add `Language.php` & update `HTTP.php` file for farsi
**Checklist:**
> [fa] add `Language.php` & update `HTTP.php` file for farsi

- Language/ja/CLI.php
- Language/ja/Validation.php
Update for v4.5.0.
**Checklist:**
> [ja] Add "CLI.generator.className.test", "Validation.field_exists"

- Language/sv-SE/CLI.php
- Language/sv-SE/Validation.php
Added missing strings in CLI and Validation.
Added the missing strings in CLI and Validation.
**Checklist:**
> [sv-SE] Added missing CLI and Validation strings

- Language/pt/CLI.php
- Language/pt/Security.php
- Language/pt/Validation.php
Added missing `Security.insecureCookie` language key
Added missing `CLI.generator.className.test` language key
Added missing `Validation.field_exists` language key
**Checklist:**
> [pt] Updated Translations

- Language/ko/CLI.php
- Language/ko/Security.php
- Language/ko/Validation.php
> [ko] Updated Translations

- .github/scripts/continuous-integration
- update coding style
**Checklist:**
> style: update coding style

- composer.json
- add `composer cs-fix`
**Checklist:**
- [] Conforms to style guide
> chore: add composer command "cs-fix"

- Language/sv-SE/Security.php
Updated with missing string in Security.php
**Checklist:**
> [sv-SE] Added missing Security.insecureCookie

- Language/fa/Security.php
> [fa] Add missing translations Security

- Language/fa/Time.php
> [fa] Update Time.php

- .php-cs-fixer.dist.php
- bin/generate-page
- bin/update-en-comments
> chore: update cs

- Language/es/CLI.php
- Language/es/Security.php
- Language/es/Validation.php
* Update CLI.php
* Update Security.php
* Update Validation.php
> [es] Add missing messages

- .php-cs-fixer.dist.php
- bin/generate-changelog
This utility script will speed up changelog entry for this repo.
**Checklist:**
> chore: add `bin/generate-changelog`

- .php-cs-fixer.dist.php
- bin/generate-changelog
- bin/generate-page
- bin/test
- bin/update-en-comments
- tests/AutoReview/TranslationsCodeTest.php
- tests/Language/AbstractTranslationTestCase.php
Fix coding styles.
**Checklist:**
> style: fix coding styles

- Language/ko/Errors.php
- Language/ko/Publisher.php
- Language/ko/Validation.php
- tests/Language/KoreanTranslationTest.php
> [ko] Add missing messages

- Language/pt-BR/Errors.php
- Language/pt-BR/Publisher.php
- Language/pt-BR/Security.php
- Language/pt-BR/Validation.php
This is a pull request to update Brazilian Portuguese (pt-BR), with this update I hope to achieve 100% language progress in codeigniter 4.6.
**Checklist:**
> [pt-BR] Updated translations

- .github/workflows/code-style.yml
Style check just needed lowest and highest PHP version.
**Checklist:**
> chore: check code style using lowest and highest PHP version

- .github/workflows/auto-review.yml
- .github/workflows/build.yml
added PHP `8.4` to Github Action.
**Checklist:**
> chore: added PHP `8.4` to Github Action

- Language/id/CLI.php
- Language/id/Errors.php
- Language/id/HTTP.php
- Language/id/Publisher.php
- Language/id/Security.php
- Language/id/Validation.php
> [id] fix: missing key `Indonesian` translation

- bin/generate-page
- page/Views/detail.php
Fixing the following:
```console
❯ php bin/generate-page
Generating details for: ar
Generating details for: bg
{
"title": "ErrorException",
"type": "ErrorException",
"code": 500,
"message": "array_sum(): Addition is not supported on type string",
"file": "/Users/paul/Workspace/codeigniter4-translations/bin/generate-page",
"line": 170,
"trace": [
{
"function": "errorHandler",
"class": "CodeIgniter\\Debug\\Exceptions",
"type": "->",
"args": [
2,
"array_sum(): Addition is not supported on type string",
"/Users/paul/Workspace/codeigniter4-translations/bin/generate-page",
170
]
},
{
"file": "/Users/paul/Workspace/codeigniter4-translations/bin/generate-page",
"line": 170,
"function": "array_sum",
"args": [
[
90.9,
100,
100,
100,
85.7,
100,
100,
100,
"Missing file",
100,
100, …
```
> fix: use `0` as percent when file is missing for `array_sum()`

- Language/pl/CLI.php
- Language/pl/Errors.php
- Language/pl/HTTP.php
- Language/pl/Publisher.php
- Language/pl/Security.php
- Language/pl/Validation.php
This PR adds missing translation messages.
**Checklist:**
> [pl] Add missing messages

- Language/sv-SE/Errors.php
- Language/sv-SE/Publisher.php
- Language/sv-SE/Validation.php
Added the missing strings from CI 4.6.1
**Checklist:**
> [sv-SE] update of sv-SE to 4.6.1
