codeigniter4/translations

Language/fr/View.php
Nothing fancy, just the corresponding french lines. I assumed that "view cell" should stay as such much like words or terms like: framework, template, etc, when encountered.
=> Some french translation

.github/scripts/continuous-integration
This is an attempt to add a short summary notice about the failed and passed locale test at the end of the test results.
Could be helpful espacially for multi-locale changes.
Still need to find a way to add the same functionality for `AllLocalesTranlationTest`.
=> Add locales summary to tests.

tests/Language/AbstractTranslationTestCase.php
This adds a test method to check whether the order of the translated keys is the same as in the main repo.
At the same time, this also protects against duplicate key definitions in translated file, but not all possible cases.
Example that will trigger an error:
'key1' => 'val1',
'key2' => 'val2',
'key1' => 'val3',
Example that will not trigger an error:
'key1' => 'val1',
'key1' => 'val3',
'key2' => 'val2',
Example output for current `it` locale:
Failed asserting that the translated language keys in "it" locale have the same order as the original keys in the main repository. This can also be caused by duplicate key definitions. First mismatch per file:
Migrations:
- 26 => 'migSeeder'
+ 26 => 'on'  
Validation:
- 26 => 'matches'
+ 26 => 'string'
Failed asserting that an array is empty.
I …
=> Add tests for translated key order and some cases of duplicate keys.

Language/ja/Cast.php, Language/ja/Core.php
Update:
- Cast.php
- Core.php
```sh-session
$ vendor/bin/phpunit --filter JapaneseTranslationTest
PHPUnit 9.5.8 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.21
Configuration: /Users/kenji/work/codeigniter/codeigniter4-translations/phpunit.xml.dist
.......                                                             7 / 7 (100%)
Time: 00:00.098, Memory: 22.00 MB
OK (7 tests, 7 assertions)
```
=> Update Cast and Core for ja

.github/scripts/continuous-integration, bin/test
From latest php-cs-fixer v3.6, scripts also get header comments if `header_comment` is on.
=> Add header comment to scripts

.php-cs-fixer.dist.php
=> Remove deprecated `Nexus/space_after_comment_start`

bin/update-en-comments
Add a script to add english strings as comments. It is used in #329.
**Note:** When you run this script, all comments after the translation strings like the following will be removed.
```php
'noDriverRequested'    => 'ドライバは不要です。', // ダジャレは翻訳しません
```
**How to Use**
```console
$ composer update
$ bin/update-en-comments bs
```
```diff
$ git diff Language/bs/Test.php
diff --git a/Language/bs/Test.php b/Language/bs/Test.php
index 91efe6d..50f3591 100644
--- a/Language/bs/Test.php
+++ b/Language/bs/Test.php
@@ -11,5 +11,5 @@
// Testing language settings
return [
-    'invalidMockClass' => '{0} nije validna Mock klasa',
+    'invalidMockClass' => '{0} nije validna Mock klasa', // '{0} is not a valid Mock class'
];
```
=> chore: add script to add en lang strings as comments

.github/workflows/auto-review.yml, .github/workflows/build.yml, .github/workflows/code-style.yml
See:
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Update action workflows

bin/update-en-comments
Before:
```diff
--- a/Language/ja/CLI.php
+++ b/Language/ja/CLI.php
@@ -18,6 +18,7 @@ return [
'cancelOperation' => '操作はキャンセルされました。', // 'Operation has been cancelled.'
'className'       => [
'cell'       => 'セルのクラス名', // 'Cell class name'
+            'cell'       => 'セルのクラス名', // 'Cell view name'
'command'    => 'コマンドクラス名', // 'Command class name'
'config'     => '設定クラス名', // 'Config class name'
'controller' => 'コントローラクラス名', // 'Controller class name'
@@ -40,6 +41,7 @@ return [
'tableName'        => 'テーブル名', // 'Table name'
'usingCINamespace' => '警告: 名前空間 "CodeIgniter" を使用するとsystemディレクトリにファイルが生成されます。', // 'Warning: Using the "CodeIgniter" namespace will generate the file in the system directory.'
'viewName'         => [
+            'cell' => 'セルのビュー名', // 'Cell class name'
'cell' => …
```
=> fix: `update-en-comments` does not work when having duplicate keys

Language/de/Files.php, Language/de/Publisher.php, Language/de/Test.php
Some DE files are encoded in "windows-1252" charset instead of UTF-8.
I think it's a mistake and after a quick research I didn't find a closed issue about this or any logic why these files are in a different encoding.
**Checklist:**
=> [de] Convert windows-1252 files to UTF-8

Language/ko/Core.php, Language/ko/Language.php
- Add Language.php
- Update Core.php
**Checklist:**
=> [ko] Add Language.php, Update Core.php

bin/generate-page, page/Views/detail.php
This PR fixes a few issues with the current `generate-page` script implementation, described below.
I have noticed a two things:
* information about `Missing keys` that are in a nested array is not displayed
* there is no information about missing files (if there are any), therefore missing files are not considered when calculating the overall translation percentage for the locale
**Checklist:**
=> fix: generate-page

Language/sv-SE/HTTP.php, Language/sv-SE/Language.php
Supersedes #424
Another try at the PR from yesterday... Updated sv_SE language with Language.php and missing JSON related strings in HTTP.php
**Checklist:**
=> [sv-SE] Update sv-SE, added Language.PHP and missing HTTP strings

LICENSE, Language/es/CLI.php, Language/es/Core.php, Language/es/Database.php, Language/es/Errors.php, Language/es/Files.php, Language/es/HTTP.php, Language/es/Language.php, Language/es/Migrations.php, Language/es/Publisher.php, Language/es/Router.php, Language/es/Test.php, Language/es/Validation.php, Language/es/View.php
* Create Errors.php
* Create Language.php
* Create Publisher.php
* Create Test.php
* Update CLI.php
* Update Core.php
* Update Database.php
* Update Files.php
* Update HTTP.php
* Update Migrations.php
* Update Router.php
* Update Validation.php
* Update View.php
=> [es] Update Spanish Translation

.github/workflows/auto-review.yml, .github/workflows/build.yml, .github/workflows/code-style.yml, tests/Language/AbstractTranslationTestCase.php
Requires https://github.com/codeigniter4/CodeIgniter4/pull/8745
- update PHP versions
- fix PHPDoc types
**Checklist:**
- [] Conforms to style guide
=> chore: update PHP versions

Language/fa/CLI.php, Language/fa/Validation.php
=> [fa] add missing keys `generator.className.test` & `field_exists`

composer.json, phpunit.xml.dist, tests/AutoReview/LicenseTest.php, tests/AutoReview/TranslationsCodeTest.php, tests/Language/AbstractTranslationTestCase.php
Updates minimum PHP version to ^8.1 to align with CodeIgniter v4.5.0 and also updates PHPUnit to 10.5 || 11.0
**Checklist:**
=> refactor: update to PHP 8.1 and PHPUnit 10.5 || 11.0

Language/ja/Security.php
Add Security.insecureCookie translation.
**Checklist:**
=> [ja] Add Security.insecureCookie translation

Language/ru/CLI.php, Language/ru/Cache.php, Language/ru/Cast.php, Language/ru/Cookie.php, Language/ru/Core.php, Language/ru/Database.php, Language/ru/Email.php, Language/ru/Encryption.php, Language/ru/Errors.php, Language/ru/Fabricator.php, Language/ru/Files.php, Language/ru/Filters.php, Language/ru/Format.php, Language/ru/HTTP.php, Language/ru/Images.php, Language/ru/Language.php, Language/ru/Migrations.php, Language/ru/Number.php, Language/ru/Pager.php, Language/ru/Publisher.php, Language/ru/RESTful.php, Language/ru/Router.php, Language/ru/Security.php, Language/ru/Session.php, Language/ru/Test.php, Language/ru/Time.php, Language/ru/Validation.php, Language/ru/View.php
I've updated the translations for Russian to match the “Language/en” file.
**Checklist:**
=> [ru] Update the comment block & added new lines

Language/ja/Cookie.php
Supersedes #473
- before text is wrong in japanese grammer. So, i fixed it.
- And i opened the same PR before, but i made a mistake in before PR.  So, i open the new one.
**Checklist:**
=> [ja] fix japanese content into right meaning.

bin/test
When running:
```cli
./bin/test pl
```
I get an error:
```cli
{
"title": "ArgumentCountError",
"type": "ArgumentCountError",
"code": 500,
"message": "Too few arguments to function PHPUnit\\Framework\\TestCase::__construct(), 0 passed in /Users/michalsn/Sites/ci4_translations/bin/test on line 36 and exactly 1 expected",
"file": "/Users/michalsn/Sites/ci4_translations/vendor/phpunit/phpunit/src/Framework/TestCase.php",
"line": 239,
"trace": [
{
"file": "/Users/michalsn/Sites/ci4_translations/bin/test",
"line": 36,
"function": "__construct",
"class": "PHPUnit\\Framework\\TestCase",
"type": "->",
"args": []
}
]
}
```
When we create an anonymous class that extends `AbstractTranslationTestCase`, that class inherits from PHPUnit's `TestCase` through the inheritance chain. The …
=> fix: test translation
